### ISSUE TITLE
Bounded Memory

### ISSUE THREAD

**Issue by BlackCapCoder** [kowainik/membrain#39]
Recently I was optimizing some code that was using regexes to search DNA strings:

```
agggtaaa|tttaccct
[cgt]gggtaaa|tttaccc[acg]
a[act]ggtaaa|tttacc[agt]t
ag[act]gtaaa|tttac[agt]ct
agg[act]taaa|ttta[agt]cct
aggg[acg]aaa|ttt[cgt]ccct
agggt[cgt]aa|tt[acg]accct
agggta[cgt]a|t[acg]taccct
agggtaa[cgt]|[acg]ttaccct
```

Conveniently, all of these are of length 8 and there are only 4 possible letters, so I can fit one of these in a `Word16`:

```haskell
-- Holds 8 DNA letters, each letter is 2 bits
type Buffer = Word16
```

And I can push a new letter to the front of my buffer and simultaneously remove the last like so:

```haskell
type DNALetter = Buffer
push :: DNALetter -> Buffer -> Buffer
push l b = shiftL b 2 .|. l
```

Searching then, is done by pushing one letter at a time and checking if the buffer matches any of the strings from the regexes.

It would be nice if the type of `DNALetter` reflected that a letter should be `2` bits long, which I can express with Membrain like so:
```haskell
type DNALetter = Memory (Bit * 2)
push :: DNALetter -> Buffer -> Buffer
push l b = shiftL b 2 .|. fromIntegral (unMemory l)
```

Now, I have 2 issues with this:
1) I believe this would make my code significantly slower because now I have to cast the letter to a Word16 from a Natural
2) It makes it possible to push more letters than my buffer can actually fit

----

I propose adding a bounded memory type

```haskell
newtype BoundedMemory (unit :: Nat) (max :: Nat) where
  { unMemory :: WordByBits (unit * max) }
```

Here, `unit` would be the same as `mem` in `Memory`, `max` would be the how many units we can hold at most, and `WordByBits` would be the smallest word big enough to store `max` units.

One possible implementation of `WordByBits`:
```haskell
import GHC.TypeLits
import Data.Word
import Numeric.Natural

type family Log2W (n :: Nat) :: * where
  Log2W 0 = Word8
  Log2W 1 = Word16
  Log2W 2 = Word32
  Log2W 3 = Word32
  Log2W 4 = Word64
  Log2W 5 = Word64
  Log2W 6 = Word64
  Log2W 7 = Word64
  Log2W _ = Natural

type WordByBits n = Log2W (Div n 8)     -- Word by number of bits
type StingyWord n = WordByBits (Log2 n) -- Word by cardinality
```

Usage example:
```haskell
type Letter = 2 * Bit
type Buffer = BoundedMemory Letter 8 -- Word16, yay!

push l b = shiftL b 2 .|. unMemory b -- No cast, I can even coerse!
```

**Comment by BlackCapCoder** [comment]
issue:
```haskell
allocate :: BoundedMemory GigaByte 16 -> IO Ptr
```

`allocate` takes an integer big enough to hold 16gb of data. I suppose it could be used to initialize the memory, but that's rather unintuitive. The correct thing to do would be to choose a word type that can hold 0-16, or perhaps this is out of scope entirely

**Comment by chshersh** [comment]
@BlackCapCoder Thanks for opening the issue! It's an interesting design point :thinking: However, I don't believe that changing the internals of `membrain` in such dramatical way so soon worth complicating the implementation. Using `Natural` is a deliberate design choice. The main focus of the library is correctness. With your _bounded_ approach, the operation of adding two values of `BoundedMemory` can overflow. Thus it requires more thinking through.

What's more importantly, it looks like the approach with `BoundedMemory` can be implemented without changing the internals of `membrain`, but on top of `membrain` instead. The last line of your `Log2W` type family can return `Memory mem` instead of `Natural` if you want to reuse all functions from `membrain`.

So I tend to close this issue as **wontfix** and encourage you to play with your idea in a separate library! At this point, it doesn't look like one approach is strictly better than the other; they both have their pros and cons. And you can implement your solution in a library like `bounded-membrain` or `bounded-memory` and then compare two libraries :slightly_smiling_face:
